name: .NET CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    # Paso 1: Checkout del código
    - uses: actions/checkout@v4

    # Paso 2: Configurar .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Paso 3: Configurar el escáner de SonarQube
    - name: Setup SonarScanner for .NET
      run: |
        dotnet tool install --global dotnet-sonarscanner
        echo "DOTNET_TOOLS_PATH=$HOME/.dotnet/tools" >> $GITHUB_ENV
        echo "PATH=$HOME/.dotnet/tools:$PATH" >> $GITHUB_ENV

    # Paso 4: Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore

    # Paso 5: Iniciar el análisis de SonarQube
    - name: Start SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"TaskSchedulerApi" \
          /d:sonar.host.url="${{ secrets.SONARQUBE_HOST }}" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

    # Paso 6: Construir el proyecto
    - name: Build
      run: dotnet build --no-restore

    # Paso 7: Ejecutar pruebas con cobertura
    - name: Test with Coverage
      run: |
        dotnet test --no-build --verbosity normal \
        --collect:"XPlat Code Coverage" \
        --results-directory ./TestResults

    # Paso 8: Finalizar el análisis de SonarQube
    - name: End SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    # Paso 9: Publicar la aplicación
    - name: Publish
      run: |
        set -e
        dotnet publish -c Release -o out
        echo "Archivos publicados:"
        ls -l out
        if [ ! -d "out" ] || [ -z "$(ls -A out)" ]; then
          echo "Error: Publicación fallida. El directorio 'out/' está vacío."
          exit 1
        fi

    # Paso 10: Realizar un backup de los archivos existentes
    - name: Backup existing files
      uses: appleboy/ssh-action@v1.2.0
      with:
       host: ${{ secrets.VPS_IP }}
       username: ${{ secrets.VPS_USERNAME }}
       passphrase: ${{ secrets.SSH_PASSPHRASE }}
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       port: ${{ secrets.SSH_PORT }}
       script: |
        BACKUP_DIR="/var/www/nagaira.com/apis/backups/task-scheduler/$(date +'%Y%m%d_%H%M%S')"
        TARGET_DIR="${{ secrets.VPS_API_PATH }}"
        echo "Creando directorio de backup en $BACKUP_DIR..."
        mkdir -p $BACKUP_DIR
        echo "Copiando archivos del target $TARGET_DIR a $BACKUP_DIR..."
        cp -r $TARGET_DIR/* $BACKUP_DIR/
        echo "Backup completado correctamente."

    # Paso 11: Desplegar a tu VPS usando SCP
    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/work/Nagaira.TaskScheduler.Api/Nagaira.TaskScheduler.Api/out/*"
        target: "/var/www/nagaira.com/apis/temporary/task-scheduler"
        overwrite: true

    # Paso 12: Mover archivos al directorio final
    - name: Move files to final directory
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          TEMP_DIR="/var/www/nagaira.com/apis/temporary/task-scheduler/github/workspace/out"
          FINAL_DIR="${{ secrets.VPS_API_PATH }}"
          echo "Moviendo archivos desde $TEMP_DIR a $FINAL_DIR..."
          
          # Crear el directorio final si no existe
          mkdir -p $FINAL_DIR

          # Mover los archivos
          mv $TEMP_DIR/* $FINAL_DIR/

          # Verificar la operación
          if [ "$(ls -A $FINAL_DIR)" ]; then
            echo "Archivos movidos exitosamente a $FINAL_DIR."
          else
            echo "Error: El directorio $FINAL_DIR está vacío después del movimiento."
            exit 1
          fi

    # Paso 13: Reiniciar el servicio en el VPS
    - name: Restart API Service
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Deteniendo el servicio api-task-scheduler.service..."
          sudo systemctl stop api-task-scheduler.service
          echo "Reiniciando el servicio api-task-scheduler.service..."
          sudo systemctl start api-task-scheduler.service
          echo "Servicio reiniciado correctamente."
