name: .NET CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    # Paso 1: Checkout del código
    - uses: actions/checkout@v4

    # Paso 2: Configurar .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Paso 3: Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore

    # Paso 4: Construir el proyecto
    - name: Build
      run: dotnet build --no-restore

    # Paso 5: Ejecutar pruebas
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Paso 6: Publicar la aplicación
    - name: Publish
      run: |
        set -e
        dotnet publish -c Release -o out
            # Listar los archivos generados
            echo "Archivos publicados:"
            ls -l out
            if [ ! -d "out" ] || [ -z "$(ls -A out)" ]; then
              echo "Error: Publicación fallida. El directorio 'out/' está vacío."
              exit 1
            fi

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        # Escribe el secreto SSH directamente en el archivo, incluyendo saltos de línea
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/nagaira_ssh_pair
        chmod 600 ~/.ssh/nagaira_ssh_pair
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      # Paso 7: Desplegar a tu VPS usando SSH
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ~/.ssh/nagaira_ssh_pair
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 2222
        script: |
          # Subir los archivos generados al VPS
          scp -P 2222 -r ./out/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:${{ secrets.VPS_API_PATH }}
          # Reiniciar el servicio en el VPS
          sudo systemctl restart api-task-scheduler.service
